Repository GarageGames/Torque3D, pull requests merged in 2018-09, with the labels that each got.

#2249 Updates PlatformCursorController to use full set of SDL cursors.
  Engine/source/windowManager/platformCursorController.h
  Engine/source/windowManager/sdl/sdlCursorController.cpp
  Engine/source/windowManager/win32/win32CursorController.cpp
Labels: Improvement

#2259 Changes TSStatic::castRayRendered to use passed texcoord argument.
  Engine/source/T3D/tsStatic.cpp
Labels: Bugfix

#2250 Fixes various incorrect popup menu behaviors.
  Engine/source/gui/editor/popupMenu.cpp
  Engine/source/gui/editor/popupMenu.h
  Templates/BaseGame/game/tools/base/menuBar/menuBuilder.ed.cs
  Templates/BaseGame/game/tools/guiEditor/scripts/guiEditorTreeView.ed.cs
  Templates/BaseGame/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/EditorGui.ed.cs
  Templates/Full/game/tools/base/menuBar/menuBuilder.ed.cs
  Templates/Full/game/tools/guiEditor/scripts/guiEditor.ed.cs
  Templates/Full/game/tools/guiEditor/scripts/guiEditorTreeView.ed.cs
  Templates/Full/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
  Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
Labels: Bugfix, Improvement
