Repository GarageGames/Torque3D, pull requests merged in 2018-05, with the labels that each got.

#2237 Small Cleanup to CodeInterpreter
  Engine/source/console/codeInterpreter.cpp
Labels: Bugfix, Improvement

#2235 Fix dumpConsoleClasses / dumpConsoleFunctions
  Engine/source/console/codeBlock.cpp
  Engine/source/console/consoleDoc.cpp
Labels: Bugfix

#2234 Remove a now-unneeded fix for offsetof on new versions of Visual Studio.
  Engine/source/console/consoleTypes.h
Labels: Improvement

#2232 PhysicalZone editing-display tools.
  Engine/source/T3D/physicalZone.cpp
  Engine/source/gfx/gfxDrawUtil.cpp
  Engine/source/gfx/gfxDrawUtil.h
Labels: Improvement

#2231 Includes some renderbin declarations that are needed for AFX
  Templates/BaseGame/game/core/renderManager.cs
  Templates/Full/game/core/scripts/client/renderManager.cs
Labels: Bugfix

#2194 update to libogg v133
  Engine/lib/libogg/CHANGES
  Engine/lib/libogg/include/ogg/ogg.h
  Engine/lib/libogg/include/ogg/os_types.h
  Engine/lib/libogg/src/bitwise.c
  Engine/lib/libogg/src/framing.c
Labels: Improvement

#2108 allows for arbitrary reskinning
  Engine/source/T3D/player.cpp
  Engine/source/T3D/shapeBase.cpp
  Engine/source/T3D/tsStatic.cpp
  Engine/source/ts/tsShapeInstance.cpp
  Engine/source/ts/tsShapeInstance.h
Labels: Improvement, New feature

#2104 Sets scale for collision primitives created in the shape editor.
  Engine/source/ts/tsCollision.cpp
Labels: Bugfix

#2233 Use a circular buffer for getReturnBuffer to prevent buffer cloberring
  Engine/source/console/compiledEval.cpp
  Engine/source/console/returnBuffer.cpp
  Engine/source/console/returnBuffer.h
  Engine/source/console/stringStack.cpp
  Engine/source/console/stringStack.h
Labels: Bugfix
