Repository GarageGames/Torque3D, pull requests merged in 2018-03, with the labels that each got.

#2090 Adds some filtering options to the console log gui
  Engine/source/gui/controls/guiConsole.cpp
  Engine/source/gui/controls/guiConsole.h
  Templates/BaseGame/game/core/console/console.gui
  Templates/BaseGame/game/core/console/main.cs
  Templates/Full/game/core/art/gui/console.gui
Labels: New feature

#2215 Expanded mesh baking functionality
  Engine/source/T3D/convexShape.cpp
  Engine/source/T3D/convexShape.h
  Engine/source/T3D/prefab.cpp
  Engine/source/T3D/prefab.h
  Engine/source/T3D/tsStatic.cpp
  Engine/source/T3D/tsStatic.h
  Engine/source/gui/worldEditor/worldEditor.cpp
  Engine/source/scene/sceneObject.h
  Engine/source/ts/collada/colladaUtils.cpp
  Engine/source/ts/collada/colladaUtils.h
  Engine/source/ts/tsShapeConstruct.cpp
Labels: New feature

#2210 switchable GPU Support
  Engine/source/main/main.cpp
Labels: Bugfix

#2200 Linux compatibility fixes
  Templates/BaseGame/game/core/shaders/postFX/fxaa/fxaaV.hlsl
  Templates/BaseGame/game/core/shaders/postFX/ssao/SSAO_Blur_P.hlsl
  Templates/BaseGame/game/core/shaders/postFX/ssao/SSAO_P.hlsl
  Templates/Full/game/art/shapes/weapons/Grenade/materials.cs
  Templates/Full/game/art/shapes/weapons/Grenade/rock_d.dds
  Templates/Full/game/art/shapes/weapons/Grenade/rock_n.dds
  Templates/Full/game/art/shapes/weapons/Grenade/rock_s.dds
  Templates/Full/game/shaders/common/postFx/fxaa/fxaaV.hlsl
  Templates/Full/game/shaders/common/postFx/ssao/SSAO_Blur_P.hlsl
  Templates/Full/game/shaders/common/postFx/ssao/SSAO_P.hlsl
  Templates/Modules/FPSGameplay/art/shapes/weapons/Grenade/materials.cs
  Templates/Modules/FPSGameplay/art/shapes/weapons/Grenade/rock_d.dds
  Templates/Modules/FPSGameplay/art/shapes/weapons/Grenade/rock_n.dds
  Templates/Modules/FPSGameplay/art/shapes/weapons/Grenade/rock_s.dds
Labels: Improvement
