Repository GarageGames/Torque3D, pull requests merged in 2018-02, with the labels that each got.

#2189 Bugfixes and improvements for the animation component and related assets
  Engine/source/T3D/assets/ShapeAnimationAsset.cpp
  Engine/source/T3D/assets/ShapeAnimationAsset.h
  Engine/source/T3D/assets/ShapeAsset.cpp
  Engine/source/T3D/components/animation/animationComponent.cpp
  Engine/source/ts/collada/colladaImport.cpp
  Templates/BaseGame/game/tools/shapeEditor/scripts/shapeEditorActions.ed.cs
Labels: Improvement

#2190 Some code cleanup on assets, entities and components, round 1
  Engine/source/T3D/assets/ImageAsset.cpp
  Engine/source/T3D/assets/ImageAsset.h
  Engine/source/T3D/assets/LevelAsset.cpp
  Engine/source/T3D/assets/ScriptAsset.cpp
  Engine/source/T3D/components/animation/animationComponent.cpp
  Engine/source/T3D/components/collision/collisionComponent.cpp
  Engine/source/T3D/components/component.cpp
  Engine/source/T3D/components/game/stateMachine.cpp
  Engine/source/T3D/components/game/stateMachine.h
  Engine/source/T3D/components/physics/playerControllerComponent.cpp
  Engine/source/T3D/components/render/meshComponent.cpp
  Engine/source/T3D/entity.cpp
  Engine/source/T3D/entity.h
  Engine/source/T3D/systems/render/meshRenderSystem.cpp
  Engine/source/gui/editor/inspector/entityGroup.cpp
Labels: Improvement

#2196 Remove nested CLASSDOC Macro
  Engine/source/console/consoleObject.h
  Engine/source/console/engineTypes.h
Labels: Improvement

#2198 Fixes up some menubar issues.
  Engine/source/gui/core/guiCanvas.cpp
  Engine/source/gui/core/guiCanvas.h
  Engine/source/gui/editor/guiMenuBar.cpp
Labels: Bugfix

#2157 Adds a new function for defining network-aware console fields on NetObjects
  Engine/source/console/consoleObject.cpp
  Engine/source/console/consoleObject.h
  Engine/source/console/simObject.cpp
  Engine/source/sim/netObject.cpp
  Engine/source/sim/netObject.h
Labels: New feature

#2202 Removes the GameObject folder insert for the scripted object creator grid
  Templates/BaseGame/game/tools/worldEditor/scripts/editorPrefs.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/editors/creator.ed.cs
  Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
  Templates/Full/game/tools/worldEditor/scripts/editorPrefs.ed.cs
  Templates/Full/game/tools/worldEditor/scripts/editors/creator.ed.cs
Labels: Bugfix
