Repository GarageGames/Torque3D, pull requests merged in 2018-12, with the labels that each got.

#2276 filter out pixel shader normalmap calcs when not in deferred mode.
  Engine/source/terrain/glsl/terrFeatureGLSL.cpp
  Engine/source/terrain/hlsl/terrFeatureHLSL.cpp
Labels: Bugfix, Final review

#2103 Adds functionality to automate convex proxy objects
  Engine/source/T3D/convexShape.h
  Engine/source/gui/worldEditor/guiConvexShapeEditorCtrl.cpp
  Engine/source/gui/worldEditor/guiConvexShapeEditorCtrl.h
  Templates/Full/game/tools/convexEditor/images/occluderProxyImage.png
  Templates/Full/game/tools/convexEditor/images/portalProxyImage.png
  Templates/Full/game/tools/convexEditor/images/triggerProxyImage.png
  Templates/Full/game/tools/convexEditor/images/zoneProxyImage.png
  Templates/Full/game/tools/convexEditor/materials.cs
Labels: Improvement, New feature

#2258 Fixes the front/back ortho views in the editors
  Engine/source/gui/worldEditor/editTSCtrl.cpp
Labels: Bugfix

#2283 Adds handlers for sdl focus events.
  Engine/source/windowManager/sdl/sdlWindow.cpp
Labels: Final review, Improvement
