Repository GarageGames/Torque3D, pull requests merged in 2019-03, with the labels that each got.

#2281 OpenALEffects
  Engine/source/sfx/openal/LoadOAL.h
  Engine/source/sfx/openal/sfxALDevice.cpp
  Engine/source/sfx/openal/sfxALDevice.h
  Engine/source/sfx/openal/sfxALVoice.cpp
  Engine/source/sfx/openal/win32/LoadOAL.cpp
  Engine/source/sfx/sfxCommon.h
  Engine/source/sfx/sfxDescription.cpp
  Engine/source/sfx/sfxDevice.h
  Engine/source/sfx/sfxEnvironment.cpp
  Engine/source/sfx/sfxSystem.cpp
  Templates/Full/game/core/scripts/client/audioEnvironments.cs
Labels: New feature

#2318 Tweaks to the Asset/Module info echo behavior to spam the console less.
  Engine/source/assets/assetManager.cpp
  Engine/source/module/moduleManager.cpp
Labels: Improvement

#2321 Updates TextEdit value when focus is lost.
  Engine/source/gui/controls/guiTextEditCtrl.cpp
Labels: Improvement

#2323 Sanity check for calling getFieldValue
  Engine/source/console/simObject.cpp
Labels: Bugfix

#2319 Initial implementation of the Scene object
  Engine/source/T3D/Scene.cpp
  Engine/source/T3D/Scene.h
  Engine/source/T3D/prefab.cpp
  Engine/source/T3D/prefab.h
  Engine/source/environment/editors/guiMeshRoadEditorCtrl.cpp
  Engine/source/environment/editors/guiRiverEditorCtrl.cpp
  Engine/source/environment/editors/guiRoadEditorCtrl.cpp
  Engine/source/gui/worldEditor/editTSCtrl.cpp
  Engine/source/gui/worldEditor/guiConvexShapeEditorCtrl.cpp
  Engine/source/gui/worldEditor/terrainEditor.cpp
  Engine/source/gui/worldEditor/worldEditor.cpp
  Engine/source/scene/simPath.cpp
  Engine/source/terrain/terrImport.cpp
  Engine/source/ts/collada/colladaLights.cpp
  Templates/BaseGame/game/core/clientServer/Core_ClientServer.cs
  Templates/BaseGame/game/core/clientServer/scripts/server/levelInfo.cs
  Templates/BaseGame/game/core/clientServer/scripts/server/levelLoad.cs
  Templates/BaseGame/game/core/clientServer/scripts/server/server.cs
  Templates/BaseGame/game/tools/convexEditor/main.cs
  Templates/BaseGame/game/tools/gui/colladaImport.ed.gui
  Templates/BaseGame/game/tools/levels/BlankRoom.mis
  Templates/BaseGame/game/tools/materialEditor/scripts/materialEditor.ed.cs
  Templates/BaseGame/game/tools/materialEditor/scripts/materialEditorUndo.ed.cs
  Templates/BaseGame/game/tools/meshRoadEditor/main.cs
  Templates/BaseGame/game/tools/missionAreaEditor/main.cs
  Templates/BaseGame/game/tools/navEditor/CreateNewNavMeshDlg.gui
  Templates/BaseGame/game/tools/navEditor/main.cs
  Templates/BaseGame/game/tools/riverEditor/main.cs
  Templates/BaseGame/game/tools/roadEditor/main.cs
  Templates/BaseGame/game/tools/shapeEditor/main.cs
  Templates/BaseGame/game/tools/worldEditor/gui/TimeAdjustGui.ed.gui
  Templates/BaseGame/game/tools/worldEditor/gui/objectBuilderGui.ed.gui
  Templates/BaseGame/game/tools/worldEditor/scripts/EditorGui.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/SelectObjectsWindow.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/editors/creator.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/editors/worldEditor.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/menuHandlers.ed.cs
  Templates/Modules/FPSGameplay/levels/Empty Terrain.mis
  Templates/Modules/FPSGameplay/levels/EmptyLevel.mis
  Templates/Modules/FPSGameplay/levels/Outpost.mis
  Templates/Modules/spectatorGameplay/levels/Empty_Room.mis
Labels: Improvement, New feature

#2320 Allows special inspectorFields to override their height
  Engine/source/gui/editor/inspector/field.cpp
  Engine/source/gui/editor/inspector/field.h
Labels: Improvement

#2325 Moves the path return from fileDialog through the returnBuffer
  Engine/source/platform/nativeDialogs/fileDialog.cpp
Labels: Bugfix

#2326 Adds visualizers for various types of colorblindness
  Templates/BaseGame/game/tools/settings.xml
  Templates/BaseGame/game/tools/worldEditor/main.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/lightViz.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgColorBlindnessVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgColorBlindnessVisualizeP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgColorBufferP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgColorBufferP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgDepthVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgDepthVisualizeP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgGlowVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgGlowVisualizeP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgLightColorVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgLightColorVisualizeP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgLightSpecularVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgLightSpecularVisualizeP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgNormalVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgNormalVisualizeP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgShadowVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgShadowVisualizeP.hlsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgSpecMapVisualizeP.glsl
  Templates/BaseGame/game/tools/worldEditor/scripts/shaders/dbgSpecMapVisualizeP.hlsl
Labels: Improvement, New feature

#2327 Adds ability to skip loading of cached dts in enumColladaForImport
  Engine/source/ts/collada/colladaImport.cpp
Labels: New feature

#2332 Fixes a crash that occurs on linux headless servers
  Engine/source/windowManager/sdl/sdlWindowMgr.cpp
Labels: Bugfix

#2322 Adds gui3DProjectionCtrl
  Engine/source/gui/controls/gui3DProjectionCtrl.cpp
  Engine/source/gui/controls/gui3DProjectionCtrl.h
Labels: New feature

#2331 Set contrsaints for Player Z rotation
  Engine/source/T3D/player.cpp
Labels: Bugfix

#2335 rewrite of NavMeshUpdateAll/NavMeshUpdateAroundObject
  Engine/source/navigation/navMesh.cpp
Labels: Bugfix, Improvement

#2144 Allow correct display of widescreen resolutions (16:9 and 16:10 ratio) on a 4:3 ratio display
  Engine/source/gfx/D3D11/gfxD3D11Device.cpp
Labels: Bugfix

#2334 Cleanup and minor tweaks to the core dir structure.
  Templates/BaseGame/game/core/Core.cs
  Templates/BaseGame/game/core/Core.module
  Templates/BaseGame/game/core/clientServer/scripts/client/connectionToServer.cs
  Templates/BaseGame/game/core/components/components/actionAnimationComponent.asset.taml
  Templates/BaseGame/game/core/components/components/aiControllerComponent.asset.taml
  Templates/BaseGame/game/core/components/components/armAnimationComponent.asset.taml
  Templates/BaseGame/game/core/components/components/game/controlObject.cs
  Templates/BaseGame/game/core/utility/Core_Utility.cs
  Templates/BaseGame/game/core/utility/scripts/gameObjectManagement.cs
  Templates/BaseGame/game/core/utility/scripts/globals.cs
  Templates/BaseGame/game/core/utility/scripts/helperFunctions.cs
  Templates/BaseGame/game/core/utility/scripts/persistanceManagement.cs
Labels: Improvement

#2336 Fixes artifacts in Cloud Layer.
  Engine/source/environment/cloudLayer.cpp
Labels: Bugfix

#2339 Adds logic to temporarily disable collisions of mounted objects on Players
  Engine/source/T3D/player.cpp
Labels: Bugfix

#2340 Makes the popups correctly operate anywhere in the space of the canvas
  Engine/source/gui/editor/popupMenu.cpp
Labels: Bugfix

#2338 Fixes some outstanding menubar problems.
  Engine/source/gui/editor/guiMenuBar.cpp
  Engine/source/gui/editor/guiMenuBar.h
  Templates/BaseGame/game/tools/physicsTools/main.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/EditorGui.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/menus.ed.cs
  Templates/Full/game/tools/physicsTools/main.cs
  Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
  Templates/Full/game/tools/worldEditor/scripts/menus.ed.cs
Labels: Bugfix

#2024 snapTo Menu
  Templates/BaseGame/game/tools/worldEditor/scripts/menuHandlers.ed.cs
  Templates/BaseGame/game/tools/worldEditor/scripts/menus.ed.cs
Labels: Improvement

#2043 cleaning the modules
  Engine/source/T3D/shapeImage.cpp
  Engine/source/ts/tsShapeConstruct.cpp
  Templates/BaseGame/game/core/shapes/materials.cs
  Templates/BaseGame/game/core/shapes/noshape.dts
  Templates/BaseGame/game/core/shapes/noshape.mb
  Templates/BaseGame/game/tools/shapes/unit_capsule.dts
  Templates/BaseGame/game/tools/shapes/unit_cube.dts
  Templates/BaseGame/game/tools/shapes/unit_sphere.dts
  Templates/Modules/FPSGameplay/art/shapes/materials.cs
  Templates/Modules/spectatorGameplay/art/shapes/base-normal.png
  Templates/Modules/spectatorGameplay/art/shapes/base.png
  Templates/Modules/spectatorGameplay/art/shapes/lightray.png
  Templates/Modules/spectatorGameplay/art/shapes/materials.cs
  Templates/Modules/spectatorGameplay/art/shapes/noshape.dts
  Templates/Modules/spectatorGameplay/art/shapes/noshape.mb
  Templates/Modules/spectatorGameplay/art/shapes/portal.dts
  Templates/Modules/spectatorGameplay/art/shapes/top-normal.png
  Templates/Modules/spectatorGameplay/art/shapes/top.png
  Templates/Modules/spectatorGameplay/art/shapes/unit_capsule.dts
  Templates/Modules/spectatorGameplay/art/shapes/unit_cube.dts
  Templates/Modules/spectatorGameplay/art/shapes/unit_sphere.dts
Labels: Improvement

#2000 Fix for bug #1975
  Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
Labels: Improvement
